import { Inject, Injectable, Logger } from '@nestjs/common'
import Redis from 'ioredis'
import { REDIS_CLIENT } from '../redis/redis.constants'

const PRESENCE_KEY = 'presence:online'

// Sliding-window TTL. Clients send a heartbeat ~every 45s; an entry counts
// as online while its score is newer than (now - PRESENCE_TTL_SECONDS). Keep
// this larger than 2× heartbeat interval so a single missed/late ping (mobile
// throttling, slow network, sleeping tab waking up) doesn't drop the user
// from the counter.
const PRESENCE_TTL_SECONDS = 90

/**
 * Online presence — one Redis sorted set, score = last-seen unix-ms,
 * member = client-supplied id.
 *
 * The model is "client tells us it's alive every N seconds, we expire it
 * after 2N". Same pattern as Discord/Slack/Steam web counters: it's the
 * only presence approach that survives flaky networks, multi-dyno
 * deployments, dyno crashes, and sleeping tabs without ghost users or
 * complex bookkeeping.
 *
 * The presence id is a UUID generated by the browser and persisted in
 * localStorage, so multiple tabs of the same browser dedupe to one online
 * user (localStorage is shared across tabs of the same origin).
 */
@Injectable()
export class PresenceService {
  private readonly logger = new Logger(PresenceService.name)

  constructor(@Inject(REDIS_CLIENT) private readonly redis: Redis) {}

  async touch(id: string): Promise<void> {
    try {
      await this.redis.zadd(PRESENCE_KEY, Date.now(), id)
    } catch (err) {
      this.logger.warn(
        `presence touch failed for ${id}: ${(err as Error).message}`,
      )
    }
  }

  async getOnlineCount(): Promise<number> {
    try {
      const cutoff = Date.now() - PRESENCE_TTL_SECONDS * 1000
      // Evict stale entries first so the count reflects truly-live clients
      // even if the user closed the tab and never sent a goodbye.
      await this.redis.zremrangebyscore(PRESENCE_KEY, '-inf', cutoff)
      return await this.redis.zcard(PRESENCE_KEY)
    } catch (err) {
      this.logger.warn(`presence read failed: ${(err as Error).message}`)
      return 0
    }
  }
}
