-- Withdrawals (Steam Skins flow).
--
-- One row per "user requests to withdraw inventory item X". Tracks the
-- TM purchase + Steam trade lifecycle from request to final state.
-- Multi-skin withdraws produce N rows in one batch — each item is its
-- own TM order so they fail / succeed independently.
--
-- Status state machine:
--   pending     — row inserted, TM purchase not yet attempted (rare,
--                 only if request was queued before the service kicked it)
--   purchasing  — TM `/buy-for` called, awaiting TM-side order status
--   delivering  — TM order matched, trade offer sent to Steam, awaiting
--                 user accept (TM signals this transition via order status)
--   completed   — Steam trade accepted by the user; item left our hands
--   failed      — TM purchase failed (no offers / price moved / Steam
--                 trade rejected). `failure_reason` carries the detail.
--                 Refund logic flips inventory.is_withdrawn=false on this.
--
-- `tm_order_id` and `custom_id`:
--   - custom_id is OUR generated id sent into TM's `customId` param.
--     TM echoes it back on status checks for idempotent matching.
--   - tm_order_id is TM's internal id, returned from `/buy-for`. We store
--     both so the polling job can use whichever TM exposes consistently.
--
-- Polymorphism: the inventory_item this row references can point at a
-- CSGO or Dota skin (UserInventory is XOR-polymorphic). `game_type`
-- mirrors UserInventory.game_type for fast filtering and so the
-- polling job knows which TM client to dispatch (market.csgo.com vs
-- market.dota2.net).

BEGIN;

CREATE TABLE IF NOT EXISTS withdrawals (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         integer NOT NULL,
  inventory_item_id integer NOT NULL,
  game_type       varchar(16) NOT NULL,
  status          varchar(32) NOT NULL DEFAULT 'pending',
  tm_order_id     varchar(128),
  custom_id       varchar(64) NOT NULL UNIQUE,
  trade_url       text NOT NULL,
  -- target_price = what we authorised TM to spend (raw_market_price).
  -- actual_price = what TM actually paid (filled in after status=completed).
  target_price    numeric(10, 2) NOT NULL,
  actual_price    numeric(10, 2),
  failure_reason  text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  completed_at    timestamptz,

  CONSTRAINT withdrawals_status_check CHECK (
    status IN ('pending', 'purchasing', 'delivering', 'completed', 'failed')
  ),
  CONSTRAINT withdrawals_game_type_check CHECK (
    game_type IN ('csgo', 'dota')
  ),
  CONSTRAINT fk_withdrawals_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_withdrawals_inventory
    FOREIGN KEY (inventory_item_id) REFERENCES user_inventory(id)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_user_id
  ON withdrawals(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status
  ON withdrawals(status)
  WHERE status IN ('pending', 'purchasing', 'delivering');
CREATE INDEX IF NOT EXISTS idx_withdrawals_inventory_item
  ON withdrawals(inventory_item_id);

-- Trigger to keep updated_at in sync. PG doesn't have ON UPDATE built-in
-- like MySQL, so we attach a small trigger. Idempotent — only created
-- if it doesn't exist yet.
CREATE OR REPLACE FUNCTION withdrawals_set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $trg$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'withdrawals_updated_at_trigger'
  ) THEN
    CREATE TRIGGER withdrawals_updated_at_trigger
      BEFORE UPDATE ON withdrawals
      FOR EACH ROW
      EXECUTE FUNCTION withdrawals_set_updated_at();
  END IF;
END
$trg$;

COMMIT;
